repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.77.1"
    hooks:
      - id: terraform_fmt
        exclude: ^.*/secrets\.(tf|yaml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^.*/secrets\.(tf|yaml)$
    -   id: end-of-file-fixer
        exclude_types:  [pem]
        exclude: ^.*/secrets\.(tf|yaml)$
    -   id: mixed-line-ending
        exclude_types:  [pem]
        exclude: ^.*/secrets\.(tf|yaml)$
    -   id: trailing-whitespace
        exclude_types:  [pem]
        exclude: ^.*/secrets\.(tf|yaml)$
